# Generated by Django 2.2 on 2019-04-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSemesterTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('start_date', models.DateTimeField(auto_created=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pcn', models.PositiveIntegerField()),
                ('is_mentor', models.BooleanField()),
                ('is_exam_board', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('start_date', models.DateTimeField(auto_created=True)),
                ('student_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pcn', models.PositiveIntegerField()),
                ('stream', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Class')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Course')),
                ('depends_on_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.CourseSemesterTeacher')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='PassedSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Semester')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(auto_created=True)),
                ('grade', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Student')),
            ],
        ),
        migrations.AddField(
            model_name='coursesemesterteacher',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Semester'),
        ),
        migrations.AddField(
            model_name='coursesemesterteacher',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyInsight.Semester'),
        ),
    ]
